# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: v1
replicaCount: 2

image:
  repository: your/image/repository
  pullPolicy: IfNotPresent
  tag: 1.24  # Update this to a specific version

service:
  type: NodePort
  port: 8080
datree:
  offline: true
  local: true

